# Generated by Django 3.1.4 on 2020-12-09 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sectionList',
            fields=[
                ('id_section', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='titleList',
            fields=[
                ('id_title', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=50)),
                ('id_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.sectionlist')),
            ],
        ),
    ]
