# Generated by Django 3.1.4 on 2020-12-12 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='titlelist',
            name='article_text',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='titlelist',
            name='id_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.sectionlist'),
        ),
    ]
