# Generated by Django 3.1.4 on 2021-01-12 08:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201212_1031'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sectionlist',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterModelOptions(
            name='titlelist',
            options={'verbose_name': 'Пост', 'verbose_name_plural': 'Посты'},
        ),
        migrations.AlterField(
            model_name='sectionlist',
            name='section',
            field=models.CharField(max_length=50, verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='titlelist',
            name='article_text',
            field=models.TextField(null=True, verbose_name='Текст'),
        ),
        migrations.AlterField(
            model_name='titlelist',
            name='id_section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.sectionlist', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='titlelist',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Пост'),
        ),
    ]
